version: "3.9"
services:
  frontend:
    build: ./frontend
    platform: linux/x86_64
    container_name: app_backend
    ports:
      - 3000:3000
    depends_on:
      backend:
        condition: service_healthy
    # The`healthcheck` should garantee that the api is working
    # before building the app
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"] # In case of ports change, change this one too.
      timeout: 10s
      retries: 5
  backend:
    build: ./backend
    platform: linux/x86_64
    container_name: app_backend
    ports:
      - 3001:3001
    restart: "always"
    # ...
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PORT=3001
      - DB_USER_DEV=root
      - DB_PWD_DEV=root123
      - HOST=db
      - DB_NAME_DEV=DESAFIO
      - PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.21
    platform: linux/x86_64
    container_name: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    restart: "always"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"] # wait for the db
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Ignore minor alerts
